<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-SURAJ" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2019-12-02T17:54:12 IST" time="0.203" errors="0">
  <testcase name="test2" time="0.031" classname="demo.TestNGRetryFailedDemo"/>
  <testcase name="test3" time="0.017" classname="demo.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:23)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="demo.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
